import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/widgets/ui/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru">
      <Header />
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center px-24 pt-6">
          {children}
        </main>
      </body>
    </html>
  )
}
